baseurl = "https://example.com/"
title = "Some Website!"
languageCode = "en-gb"
paginate = "5" # Number of posts per page
theme = "menhir"
disqusShortname = "" # Enable comments by entering your Disqus shortname

[Author]
    name = "Joe Bloggs"
    bio = "Some dude called Joe Bloggs"
    avatar = "images/avatar.jpg"

[Params]
    author_box = true
    subtitle = "Look, monkeys!" # Subtitle of your site
    bulma_theme = "lux" # bulmaswatch theme - see https://jenil.github.io/bulmaswatch/
    post_sections = ["blog"] # Name sections here that you want to show up on the front page and in the recent articles widget
    post_navigation = true # set to false to disable category based navigation links on article pages
    custom_css = []
    custom_js = []
    social_twitter = "" # Fill in any of the social_* variables to enable links to your social pages in the navbar
    social_github = ""
    social_facebook = ""

[Params.widgets]
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget

[[menu.main]]
	name = "Blog"
	url = "/categories/blog/"