baseurl = "https://example.com/"
title = "Some Website!"
languageCode = "en-gb"
paginate = "5" # Number of posts per page
theme = "menhir"
disqusShortname = "" # Enable comments by entering your Disqus shortname

[Author]
    name = "Joe Bloggs"
    bio = "Some dude called Joe Bloggs"
    avatar = "images/avatar.jpg"

[Params]
    bulma_theme = "lux" # bulmaswatch theme - see https://jenil.github.io/bulmaswatch/
    subtitle = "Look, monkeys!" # Subtitle of your site
    post_sections = ["blog"] # Name sections here that you want to show up on the front page and in the recent articles widget
    post_navigation = true
    #description = "Opinions from a code monkey" # Description of your site
    author_box = true
    custom_css = []
    custom_js = []

[Params.widgets]
    social = true # Enable social media links
    social_twitter = ""
    social_github = ""
    social_facebook = ""
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget

[[menu.main]]
	name = "Blog"
	url = "/categories/blog/"